### ISSUE TITLE
"aws_ssm_parameter" "wg_server_private_key":

### ISSUE THREAD

**Issue by davidkarlsen** [jmhale/terraform-aws-wireguard#7] opened 2020-01-24 01:19 UTC
I always get:
```
Error: Error describing SSM parameter: ParameterNotFound: 

  on .terraform/modules/vpc.wireguard/wireguard-ssm.tf line 1, in data "aws_ssm_parameter" "wg_server_private_key":
   1: data "aws_ssm_parameter" "wg_server_private_key" {
```

either I set the param to:
`  wg_server_private_key_param = "/wireguard/wg-server-private-key"`
or not.

the param has been set via the cli - I've double checked.

**Comment by jmhale** [comment] 2020-02-21 10:07
@davidkarlsen Just to be sure, you're getting back a value similar to this when calling `aws ssm get-parameter --name /wireguard/wg-server-private-key`

```
{
    "Parameter": {
        "Name": "/wireguard/wg-server-private-key",
        "Type": "SecureString",
        "Value": "REDACTED",
        "Version": 2,
        "LastModifiedDate": "2019-02-24T15:52:45.964000-05:00",
        "ARN": "arn:aws:ssm:us-east-1:REDACTED:parameter/wireguard/wg-server-private-key"
    }
}
```

Also, make sure to grab the latest master. There were some changes with how that param path is being set. I don't think it's related to your issue, but it can't hurt to check.

I'm not able to reproduce on my end, unless I override the default path with an intentionally incorrect value.

**Comment by davidkarlsen** [comment] 2020-02-21 12:28
Thanks for getting back - in the mean time I went for vanilla IPSEC with AWS.

**Comment by jmhale** [comment] 2020-02-21 14:07
Sounds good. I'll close this, since I can't reproduce and I haven't seen reports elsewhere of this happening. Feel free to re-open if you still encounter this issue.

**Closed by jmhale** 2020-02-21 14:07 UTC

**Comment by bthibault** [comment] 2020-12-11 19:50
I ran into the same issue . Its because I have multiple aws profiles. 

So i had to modify providers.tf 

provider "aws" {
  version = "~> 2.0"
  region = "us-east-1"
  profile = "my-aws-profile"

}
